"""
report_generator.py
--------------------
Compiles results from the various SecureNet Guardian modules into a
single, professional security assessment report, exportable as HTML
and PDF.

PDF generation uses reportlab. HTML generation uses a lightweight
inline template so the toolkit has no external templating
dependency.

Author: SecureNet Guardian Team
"""

import os

from utils import print_success, print_info, ensure_dir, timestamp, file_timestamp

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    )
    from reportlab.lib.units import cm
    REPORTLAB_AVAILABLE = True
except ImportError:  # pragma: no cover
    REPORTLAB_AVAILABLE = False


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>SecureNet Guardian - Security Assessment Report</title>
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a1a; background:#f7f9fb; }}
    h1 {{ color: #0b3d91; border-bottom: 3px solid #0b3d91; padding-bottom: 8px; }}
    h2 {{ color: #12507b; margin-top: 30px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
    th, td {{ border: 1px solid #ccc; padding: 8px 12px; text-align: left; font-size: 14px; }}
    th {{ background-color: #0b3d91; color: white; }}
    tr:nth-child(even) {{ background-color: #eef2f7; }}
    .meta {{ color: #555; font-size: 13px; margin-bottom: 20px; }}
    .risk-high {{ color: #b00020; font-weight: bold; }}
    .footer {{ margin-top: 40px; font-size: 12px; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }}
</style>
</head>
<body>
    <h1>SecureNet Guardian &mdash; Security Assessment Report</h1>
    <div class="meta">Generated on {generated_at} &nbsp;|&nbsp; Target: {target}</div>

    <h2>1. Open Ports &amp; Services</h2>
    {ports_table}

    <h2>2. Potential Risk Findings</h2>
    {risks_table}

    <h2>3. Password Strength Summary</h2>
    {password_section}

    <h2>4. File Integrity Summary</h2>
    {integrity_section}

    <div class="footer">
        Generated by SecureNet Guardian Toolkit &middot; For authorized educational use only.
    </div>
</body>
</html>
"""


def _dict_list_to_html_table(rows, columns):
    if not rows:
        return "<p><em>No data available.</em></p>"

    header = "".join(f"<th>{col}</th>" for col in columns)
    body_rows = ""
    for row in rows:
        cells = "".join(f"<td>{row.get(col, '')}</td>" for col in columns)
        body_rows += f"<tr>{cells}</tr>"

    return f"<table><tr>{header}</tr>{body_rows}</table>"


def generate_html_report(target, open_ports=None, risky_findings=None,
                          password_report=None, integrity_report=None,
                          output_dir="sample_outputs"):
    """
    Assemble an HTML security report from module outputs.

    Returns:
        str: path to the generated HTML file.
    """
    ensure_dir(output_dir)

    ports_table = _dict_list_to_html_table(
        open_ports or [], ["port", "service", "risk_note"]
    )
    risks_table = _dict_list_to_html_table(
        risky_findings or [], ["port", "service", "risk_note"]
    )

    if password_report:
        password_section = (
            f"<p>Strength: <strong>{password_report['strength_label']}</strong> "
            f"({password_report['score']}/4) &mdash; "
            f"Entropy: {password_report['entropy_bits']} bits</p>"
        )
    else:
        password_section = "<p><em>No password analysis performed.</em></p>"

    if integrity_report:
        integrity_section = (
            f"<p>Unchanged: {len(integrity_report['unchanged'])} | "
            f"Modified: {len(integrity_report['modified'])} | "
            f"Missing: {len(integrity_report['missing'])}</p>"
        )
    else:
        integrity_section = "<p><em>No integrity check performed.</em></p>"

    html_content = HTML_TEMPLATE.format(
        generated_at=timestamp(),
        target=target,
        ports_table=ports_table,
        risks_table=risks_table,
        password_section=password_section,
        integrity_section=integrity_section,
    )

    output_path = os.path.join(output_dir, f"report_{file_timestamp()}.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    print_success(f"HTML report generated: {output_path}")
    return output_path


def generate_pdf_report(target, open_ports=None, risky_findings=None,
                         password_report=None, integrity_report=None,
                         output_dir="sample_outputs"):
    """
    Assemble a PDF security report from module outputs using reportlab.

    Returns:
        str | None: path to the generated PDF file, or None if
        reportlab is not installed.
    """
    if not REPORTLAB_AVAILABLE:
        print_info("reportlab is not installed; skipping PDF generation.")
        return None

    ensure_dir(output_dir)
    output_path = os.path.join(output_dir, f"report_{file_timestamp()}.pdf")

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Heading1"], textColor=colors.HexColor("#0b3d91")
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], textColor=colors.HexColor("#12507b")
    )

    doc = SimpleDocTemplate(output_path, pagesize=A4)
    story = [
        Paragraph("SecureNet Guardian — Security Assessment Report", title_style),
        Paragraph(f"Generated on {timestamp()} | Target: {target}", styles["Normal"]),
        Spacer(1, 0.5 * cm),
    ]

    story.append(Paragraph("Open Ports & Services", heading_style))
    if open_ports:
        table_data = [["Port", "Service", "Risk Note"]] + [
            [str(p["port"]), p["service"], p["risk_note"]] for p in open_ports
        ]
        table = Table(table_data, colWidths=[3 * cm, 4 * cm, 9 * cm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0b3d91")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No open ports recorded.", styles["Normal"]))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("Potential Risk Findings", heading_style))
    if risky_findings:
        for finding in risky_findings:
            story.append(
                Paragraph(
                    f"Port {finding['port']} ({finding['service']}): {finding['risk_note']}",
                    styles["Normal"],
                )
            )
    else:
        story.append(Paragraph("No risky services flagged.", styles["Normal"]))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("Password Strength Summary", heading_style))
    if password_report:
        story.append(
            Paragraph(
                f"Strength: {password_report['strength_label']} "
                f"({password_report['score']}/4), "
                f"Entropy: {password_report['entropy_bits']} bits",
                styles["Normal"],
            )
        )
    else:
        story.append(Paragraph("No password analysis performed.", styles["Normal"]))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("File Integrity Summary", heading_style))
    if integrity_report:
        story.append(
            Paragraph(
                f"Unchanged: {len(integrity_report['unchanged'])}, "
                f"Modified: {len(integrity_report['modified'])}, "
                f"Missing: {len(integrity_report['missing'])}",
                styles["Normal"],
            )
        )
    else:
        story.append(Paragraph("No integrity check performed.", styles["Normal"]))

    doc.build(story)
    print_success(f"PDF report generated: {output_path}")
    return output_path
